// DealHunter.Web/src/app/shared/components/ui/stat-card/stat-card.component.ts
import { Component, input, computed } from '@angular/core';

export type StatCardVariant = 'green' | 'purple' | 'blue';

@Component({
  selector: 'app-stat-card',
  standalone: true,
  template: `
    <div
      class="stat-card"
      [style.border-color]="accentColor() + '40'"
      [style.box-shadow]="'0 0 15px rgba(0, 0, 0, 0.5), inset 0 0 15px ' + accentColor() + '0a'"
    >
      <div class="stat-info">
        <span class="stat-label">{{ label() }}</span>
        <span
          class="stat-value"
          [style.color]="accentColor()"
          [style.text-shadow]="'0 0 10px ' + accentColor() + '60'"
        >
          {{ value() }}
        </span>
        @if (subtext()) {
          <span class="stat-subtext">{{ subtext() }}</span>
        }
      </div>

      <div
        class="stat-icon-box"
        [style.background]="accentColor() + '15'"
        [style.border-color]="accentColor() + '30'"
        [style.color]="accentColor()"
      >
        <svg [lucideIcon]="icon()" [size]="24"></svg>
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: block;
    }
    .stat-card {
      background: var(--panel-bg);
      border: 1px solid;
      border-radius: 4px;
      padding: 1.2rem;
      display: flex;
      align-items: center;
      justify-content: space-between;
      position: relative;
      overflow: hidden;
    }
    .stat-info {
      display: flex;
      flex-direction: column;
      gap: 0.3rem;
    }
    .stat-label {
      font-size: 0.75rem;
      color: var(--text-muted);
      font-family: var(--font-mono);
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .stat-value {
      font-size: 1.8rem;
      font-weight: bold;
      font-family: var(--font-heading);
    }
    .stat-subtext {
      font-size: 0.75rem;
      color: var(--text-muted);
    }
    .stat-icon-box {
      padding: 0.8rem;
      border-radius: 8px;
      border: 1px solid;
      display: flex;
      align-items: center;
      justify-content: center;
    }
  `]
})
export class StatCardComponent {
  label = input<string>('');
  value = input<string | number>('');
  subtext = input<string>('');
  icon = input<string>('activity');
  variant = input<StatCardVariant>('green');

  accentColor = computed(() => {
    switch (this.variant()) {
      case 'purple':
        return 'var(--neon-purple)';
      case 'blue':
        return '#00e5ff';
      case 'green':
      default:
        return 'var(--neon-green)';
    }
  });
}

// DealHunter.Web/src/shared/components/ui/StatCard.tsx
import React from 'react';
import { LucideIcon } from 'lucide-react';

interface StatCardProps {
  label: string;
  value: string | number;
  subtext?: string;
  icon: LucideIcon;
  variant?: 'green' | 'purple' | 'blue';
}

export const StatCard: React.FC<StatCardProps> = ({
  label,
  value,
  subtext,
  icon: Icon,
  variant = 'green',
}) => {
  const accentColor =
    variant === 'purple'
      ? 'var(--neon-purple)'
      : variant === 'blue'
      ? '#00e5ff'
      : 'var(--neon-green)';

  return (
    <div
      style={{
        background: 'var(--panel-bg)',
        border: `1px solid ${accentColor}40`,
        borderRadius: '4px',
        padding: '1.2rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        position: 'relative',
        overflow: 'hidden',
        boxShadow: `0 0 15px rgba(0, 0, 0, 0.5), inset 0 0 15px ${accentColor}0a`,
      }}
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.3rem' }}>
        <span
          style={{
            fontSize: '0.75rem',
            color: 'var(--text-muted)',
            fontFamily: 'var(--font-mono)',
            textTransform: 'uppercase',
            letterSpacing: '1px',
          }}
        >
          {label}
        </span>
        <span
          style={{
            fontSize: '1.8rem',
            fontWeight: 'bold',
            fontFamily: 'var(--font-heading)',
            color: accentColor,
            textShadow: `0 0 10px ${accentColor}60`,
          }}
        >
          {value}
        </span>
        {subtext && (
          <span
            style={{
              fontSize: '0.75rem',
              color: 'var(--text-muted)',
            }}
          >
            {subtext}
          </span>
        )}
      </div>

      <div
        style={{
          padding: '0.8rem',
          borderRadius: '8px',
          background: `${accentColor}15`,
          border: `1px solid ${accentColor}30`,
          color: accentColor,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Icon size={24} />
      </div>
    </div>
  );
};
