// DealHunter.Web/src/pages/Dashboard.tsx
import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '@/shared/context/AuthContext';
import { Layout } from '@/shared/layout/Layout';
import { Panel } from '@/shared/components/ui/Panel';
import { Button } from '@/shared/components/ui/Button';
import { AlertPanel } from '@/shared/components/ui/AlertPanel';
import { RuleCard } from '@/features/rules/components/RuleCard';
import { AddRuleForm } from '@/features/rules/components/AddRuleForm';
import { getRules, createRule, deleteRule } from '@/features/rules/api/rulesApi';
import { ApiError } from '@/lib/api';
import { RuleItem } from '@/shared/types/models';
import { ConfirmModal } from '@/shared/components/ui/ConfirmModal';
import { StatCard } from '@/shared/components/ui/StatCard';
import { RefreshCw, X, Plus, Radio, Send, Activity } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export function Dashboard() {
  const { pin, logout } = useAuth();
  const [activeTab, setActiveTab] = useState('monitor');
  const [rules, setRules] = useState<RuleItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [isAddRuleOpen, setIsAddRuleOpen] = useState(() => window.innerWidth > 768);
  const [ruleToDelete, setRuleToDelete] = useState<RuleItem | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  const fetchRulesData = useCallback(
    async (isInitial = false) => {
      if (isInitial) {
        setIsLoading(true);
      } else {
        setIsRefreshing(true);
      }
      setErrorMsg(null);

      try {
        const fetchedRules = await getRules(pin);
        setRules(fetchedRules);
      } catch (err) {
        if (err instanceof ApiError && err.status === 401) {
          logout();
          return;
        }
        setErrorMsg('Unable to connect to server.');
      } finally {
        setIsLoading(false);
        setIsRefreshing(false);
      }
    },
    [pin, logout]
  );

  useEffect(() => {
    fetchRulesData(true);

    const intervalId = setInterval(() => {
      if (document.visibilityState === 'visible') {
        fetchRulesData(false);
      }
    }, 30000);

    return () => clearInterval(intervalId);
  }, [fetchRulesData]);

  const handleAddRule = async (url: string, maxPrice: number | null) => {
    setErrorMsg(null);
    const tempId = `temp-${Date.now()}`;
    const nowIso = new Date().toISOString().replace('T', ' ').substring(0, 19);
    const tempRule: RuleItem = {
      id: tempId,
      url,
      maxPrice,
      createdAt: nowIso,
    };

    setRules((prevRules) => [tempRule, ...prevRules]);

    try {
      await createRule(url, maxPrice, pin);
      await fetchRulesData(false);
    } catch (err) {
      setRules((prevRules) => prevRules.filter((r) => r.id !== tempId));

      if (err instanceof ApiError && err.status === 401) {
        logout();
        return;
      }
      const message = err instanceof Error ? err.message : 'Server rejected request';
      setErrorMsg(`Failed to create rule: ${message}`);
    }
  };

  const handleConfirmDelete = async () => {
    if (!ruleToDelete) return;
    const targetId = ruleToDelete.id;
    const targetRule = ruleToDelete;
    setRuleToDelete(null);
    setIsDeleting(true);
    setErrorMsg(null);

    setRules((prevRules) => prevRules.filter((r) => r.id !== targetId));

    try {
      await deleteRule(targetId, pin);
      await fetchRulesData(false);
    } catch (err) {
      setRules((prevRules) => {
        if (prevRules.some((r) => r.id === targetId)) return prevRules;
        return [...prevRules, targetRule];
      });

      if (err instanceof ApiError && err.status === 401) {
        logout();
        return;
      }
      const message = err instanceof Error ? err.message : 'Server rejected request';
      setErrorMsg(`Failed to delete rule: ${message}`);
    } finally {
      setIsDeleting(false);
    }
  };

  return (
    <Layout activeTab={activeTab} onTabChange={setActiveTab}>
      {activeTab === 'monitor' && (
        <>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: '1rem',
            }}
          >
            <StatCard
              label="Active Rules"
              value={rules.length}
              subtext="Monitoring 24/7"
              icon={Radio}
              variant="green"
            />
            <StatCard
              label="Alert Delivery"
              value="Telegram"
              subtext="Instant notifications"
              icon={Send}
              variant="purple"
            />
            <StatCard
              label="Engine Status"
              value="30s Poll"
              subtext="Auto-sync active"
              icon={Activity}
              variant="blue"
            />
          </div>

          {errorMsg && (
            <AlertPanel
              message={errorMsg}
              onRetry={() => fetchRulesData(false)}
              isRetrying={isRefreshing}
            />
          )}

          <Panel
            title="Active Rules"
            action={
              <button
                onClick={() => setIsAddRuleOpen((prev) => !prev)}
                style={{
                  background: isAddRuleOpen ? 'rgba(255, 7, 58, 0.15)' : 'rgba(57, 255, 20, 0.15)',
                  border: `1px solid ${isAddRuleOpen ? 'var(--neon-red)' : 'var(--neon-green)'}`,
                  color: isAddRuleOpen ? 'var(--neon-red)' : 'var(--neon-green)',
                  width: '36px',
                  height: '36px',
                  borderRadius: '4px',
                  display: 'inline-flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  cursor: 'pointer',
                  transition: 'all 0.3s ease',
                  boxShadow: isAddRuleOpen
                    ? '0 0 10px rgba(255, 7, 58, 0.3)'
                    : '0 0 10px rgba(57, 255, 20, 0.3)',
                }}
                title={isAddRuleOpen ? 'Close Form' : 'Add Rule'}
              >
                {isAddRuleOpen ? <X size={20} /> : <Plus size={20} />}
              </button>
            }
          >
            <AnimatePresence initial={false}>
              {isAddRuleOpen && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  transition={{ duration: 0.25, ease: 'easeInOut' }}
                  style={{ overflow: 'hidden', marginBottom: '1.2rem', paddingBottom: '0.8rem', borderBottom: '1px dashed var(--text-muted)' }}
                >
                  <AddRuleForm onAddRule={(url, maxPrice) => {
                    handleAddRule(url, maxPrice);
                    if (window.innerWidth <= 768) {
                      setIsAddRuleOpen(false);
                    }
                  }} />
                </motion.div>
              )}
            </AnimatePresence>

            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '1rem',
              }}
            >
                <span
                  style={{
                    color: 'var(--text-muted)',
                    fontSize: '0.85rem',
                    fontFamily: 'var(--font-mono)',
                  }}
                >
                  Active rules: {rules.length}
                </span>

                <Button
                  variant="ghost"
                  onClick={() => fetchRulesData(false)}
                  disabled={isRefreshing || isLoading}
                  style={{
                    padding: '0.4rem 0.8rem',
                    fontSize: '0.85rem',
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '0.4rem',
                  }}
                >
                  <RefreshCw
                    size={14}
                    className={isRefreshing ? 'spin-animation' : ''}
                  />
                  {isRefreshing ? 'Refreshing...' : 'Refresh'}
                </Button>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '1.2rem' }}>
                {isLoading ? (
                  Array.from({ length: 3 }).map((_, index) => (
                    <div
                      key={index}
                      style={{
                        padding: '1.2rem',
                        background: 'rgba(0, 0, 0, 0.4)',
                        border: '1px dashed var(--text-muted)',
                        opacity: 0.6,
                      }}
                    >
                      <div
                        style={{
                          height: '16px',
                          width: '40%',
                          background: 'var(--text-muted)',
                          marginBottom: '0.8rem',
                        }}
                      />
                      <div
                        style={{
                          height: '14px',
                          width: '80%',
                          background: 'rgba(255, 255, 255, 0.1)',
                        }}
                      />
                    </div>
                  ))
                ) : rules.length === 0 ? (
                  <p style={{ color: 'var(--text-muted)' }}>
                    No active monitoring rules found.
                  </p>
                ) : (
                  <AnimatePresence mode="popLayout">
                    {rules.map((rule) => (
                      <motion.div
                        key={rule.id}
                        initial={{ opacity: 0, y: -10, scale: 0.98 }}
                        animate={{ opacity: 1, y: 0, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.95, x: -20 }}
                        transition={{ duration: 0.25, ease: 'easeOut' }}
                        layout
                      >
                        <RuleCard rule={rule} onDelete={() => setRuleToDelete(rule)} />
                      </motion.div>
                    ))}
                  </AnimatePresence>
                )}
              </div>
            </Panel>
          </>
        )}

      {activeTab === 'logs' && (
        <Panel title="System Logs">
          <p style={{ color: 'var(--neon-purple)', marginBottom: '0.8rem' }}>
            Monitoring engine running normally.
          </p>
          <div
            style={{
              background: 'rgba(0,0,0,0.5)',
              padding: '1rem',
              borderRadius: '4px',
              color: 'var(--text-muted)',
              fontSize: '0.9rem',
              lineHeight: '1.6',
            }}
          >
            <div>[2026-07-23 19:55:01] INFO: Engine poll tick complete. 0 new matches.</div>
            <div>[2026-07-23 19:50:01] INFO: Engine poll tick complete. 1 match detected and dispatched to Telegram.</div>
            <div>[2026-07-23 19:45:01] INFO: Engine poll tick complete. 0 new matches.</div>
          </div>
        </Panel>
      )}

      {activeTab === 'settings' && (
        <Panel title="Settings">
          <p style={{ color: 'var(--text-main)', marginBottom: '0.8rem' }}>
            System Configuration
          </p>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.95rem', lineHeight: '1.8' }}>
            <div>Telegram Notifications: Enabled</div>
            <div>Auto-Poll Interval: 30 Seconds</div>
            <div>Theme: Neon Dark</div>
          </div>
        </Panel>
      )}

      <ConfirmModal
        isOpen={Boolean(ruleToDelete)}
        title="Delete Search Rule"
        message={
          ruleToDelete
            ? `Are you sure you want to delete the search rule for "${ruleToDelete.url.substring(0, 50)}..."?`
            : ''
        }
        confirmLabel="Delete Rule"
        cancelLabel="Cancel"
        onConfirm={handleConfirmDelete}
        onCancel={() => setRuleToDelete(null)}
        isLoading={isDeleting}
      />
    </Layout>
  );
}

// DealHunter.Web/src/app/pages/dashboard/dashboard.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { RulesService } from '../../features/rules/rules.service';
import { LayoutComponent } from '../../shared/layout/layout.component';
import { StatCardComponent } from '../../shared/components/ui/stat-card/stat-card.component';
import { AlertPanelComponent } from '../../shared/components/ui/alert-panel/alert-panel.component';
import { PanelComponent } from '../../shared/components/ui/panel/panel.component';
import { RuleCardComponent } from '../../features/rules/rule-card/rule-card.component';
import { AddRuleFormComponent } from '../../features/rules/add-rule-form/add-rule-form.component';
import { ButtonComponent } from '../../shared/components/ui/button/button.component';
import { ConfirmModalComponent } from '../../shared/components/ui/confirm-modal/confirm-modal.component';
import { RuleItem } from '../../shared/models/rule.model';
import { LucideRefreshCw, LucideX, LucidePlus } from '@lucide/angular';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    LayoutComponent,
    StatCardComponent,
    AlertPanelComponent,
    PanelComponent,
    RuleCardComponent,
    AddRuleFormComponent,
    ButtonComponent,
    ConfirmModalComponent,
    LucideRefreshCw,
    LucideX,
    LucidePlus
  ],
  template: `
    <app-layout [activeTab]="activeTab()" (onTabChange)="activeTab.set($event)">
      @if (activeTab() === 'monitor') {
        <div class="stat-grid">
          <app-stat-card
            label="Active Rules"
            [value]="rulesService.rules().length"
            subtext="Monitoring 24/7"
            icon="radio"
            variant="green"
          ></app-stat-card>
          <app-stat-card
            label="Alert Delivery"
            value="Telegram"
            subtext="Instant notifications"
            icon="send"
            variant="purple"
          ></app-stat-card>
          <app-stat-card
            label="Engine Status"
            value="30s Poll"
            subtext="Auto-sync active"
            icon="activity"
            variant="blue"
          ></app-stat-card>
        </div>

        @if (rulesService.error()) {
          <app-alert-panel
            [message]="rulesService.error()!"
            (onRetry)="handleRefresh()"
            [isRetrying]="isRefreshing()"
          ></app-alert-panel>
        }

        <app-panel title="Active Rules">
          <button
            panel-action
            (click)="toggleAddRule()"
            class="add-rule-toggle-btn"
            [class.open]="isAddRuleOpen()"
            [title]="isAddRuleOpen() ? 'Close Form' : 'Add Rule'"
          >
            @if (isAddRuleOpen()) {
              <svg lucideX [size]="20"></svg>
            } @else {
              <svg lucidePlus [size]="20"></svg>
            }
          </button>

          @if (isAddRuleOpen()) {
            <div class="add-rule-container">
              <app-add-rule-form (onAddRule)="handleAddRule($event)"></app-add-rule-form>
            </div>
          }

          <div class="rules-list-header">
            <span class="active-rules-count">Active rules: {{ rulesService.rules().length }}</span>

            <app-button
              variant="ghost"
              (onClick)="handleRefresh()"
              [disabled]="isRefreshing() || rulesService.loading()"
            >
              <span class="btn-inner">
                <svg lucideRefreshCw [size]="14" [class.spin-animation]="isRefreshing()"></svg>
                {{ isRefreshing() ? 'Refreshing...' : 'Refresh' }}
              </span>
            </app-button>
          </div>

          <div class="rules-list-body">
            @if (rulesService.loading() && rulesService.rules().length === 0) {
              @for (i of [1, 2, 3]; track i) {
                <div class="skeleton-card">
                  <div class="skeleton-title"></div>
                  <div class="skeleton-url"></div>
                </div>
              }
            } @else if (rulesService.rules().length === 0) {
              <p class="empty-text">No active monitoring rules found.</p>
            } @else {
              @for (rule of rulesService.rules(); track rule.id) {
                <app-rule-card [rule]="rule" (onDelete)="initiateDelete($event)"></app-rule-card>
              }
            }
          </div>
        </app-panel>
      }

      @if (activeTab() === 'logs') {
        <app-panel title="System Logs">
          <p class="log-status-text">Monitoring engine running normally.</p>
          <div class="log-console-box">
            <div>[2026-07-23 19:55:01] INFO: Engine poll tick complete. 0 new matches.</div>
            <div>[2026-07-23 19:50:01] INFO: Engine poll tick complete. 1 match detected and dispatched to Telegram.</div>
            <div>[2026-07-23 19:45:01] INFO: Engine poll tick complete. 0 new matches.</div>
          </div>
        </app-panel>
      }

      @if (activeTab() === 'settings') {
        <app-panel title="Settings">
          <p class="settings-title-text">System Configuration</p>
          <div class="settings-list-box">
            <div>Telegram Notifications: Enabled</div>
            <div>Auto-Poll Interval: 30 Seconds</div>
            <div>Theme: Neon Dark</div>
          </div>
        </app-panel>
      }

      <app-confirm-modal
        [isOpen]="!!ruleToDelete()"
        title="Delete Search Rule"
        [message]="getDeleteMessage()"
        confirmLabel="Delete Rule"
        cancelLabel="Cancel"
        [isLoading]="isDeleting()"
        (onConfirm)="handleConfirmDelete()"
        (onCancel)="ruleToDelete.set(null)"
      ></app-confirm-modal>
    </app-layout>
  `,
  styles: [`
    :host {
      display: block;
    }
    .stat-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 1rem;
      margin-bottom: 1.5rem;
    }
    .add-rule-toggle-btn {
      background: rgba(57, 255, 20, 0.15);
      border: 1px solid var(--neon-green);
      color: var(--neon-green);
      width: 36px;
      height: 36px;
      border-radius: 4px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      transition: all 0.3s ease;
      box-shadow: 0 0 10px rgba(57, 255, 20, 0.3);
    }
    .add-rule-toggle-btn.open {
      background: rgba(255, 7, 58, 0.15);
      border-color: var(--neon-red);
      color: var(--neon-red);
      box-shadow: 0 0 10px rgba(255, 7, 58, 0.3);
    }
    .add-rule-container {
      overflow: hidden;
      margin-bottom: 1.2rem;
      padding-bottom: 0.8rem;
      border-bottom: 1px dashed var(--text-muted);
      animation: slideDown 0.25s ease-in-out;
    }
    .rules-list-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1rem;
    }
    .active-rules-count {
      color: var(--text-muted);
      font-size: 0.85rem;
      font-family: var(--font-mono);
    }
    .btn-inner {
      padding: 0.2rem 0.4rem;
      font-size: 0.85rem;
      display: inline-flex;
      align-items: center;
      gap: 0.4rem;
    }
    .rules-list-body {
      display: flex;
      flex-direction: column;
      gap: 1.2rem;
    }
    .skeleton-card {
      padding: 1.2rem;
      background: rgba(0, 0, 0, 0.4);
      border: 1px dashed var(--text-muted);
      opacity: 0.6;
    }
    .skeleton-title {
      height: 16px;
      width: 40%;
      background: var(--text-muted);
      margin-bottom: 0.8rem;
    }
    .skeleton-url {
      height: 14px;
      width: 80%;
      background: rgba(255, 255, 255, 0.1);
    }
    .empty-text {
      color: var(--text-muted);
    }
    .log-status-text {
      color: var(--neon-purple);
      margin-bottom: 0.8rem;
    }
    .log-console-box {
      background: rgba(0,0,0,0.5);
      padding: 1rem;
      border-radius: 4px;
      color: var(--text-muted);
      font-size: 0.9rem;
      line-height: 1.6;
      font-family: var(--font-mono);
    }
    .settings-title-text {
      color: var(--text-main);
      margin-bottom: 0.8rem;
    }
    .settings-list-box {
      color: var(--text-muted);
      font-size: 0.95rem;
      line-height: 1.8;
      font-family: var(--font-mono);
    }
    @keyframes slideDown {
      from { opacity: 0; transform: translateY(-10px); }
      to { opacity: 1; transform: translateY(0); }
    }
  `]
})
export class DashboardComponent implements OnInit {
  readonly rulesService = inject(RulesService);

  activeTab = signal<'monitor' | 'logs' | 'settings'>('monitor');
  isRefreshing = signal<boolean>(false);
  isAddRuleOpen = signal<boolean>(typeof window !== 'undefined' ? window.innerWidth > 768 : true);
  ruleToDelete = signal<RuleItem | null>(null);
  isDeleting = signal<boolean>(false);

  ngOnInit(): void {
    this.rulesService.startPolling();
  }

  toggleAddRule(): void {
    this.isAddRuleOpen.update(v => !v);
  }

  async handleRefresh(): Promise<void> {
    this.isRefreshing.set(true);
    try {
      await this.rulesService.fetchRules();
    } catch {
      // Error is handled in service
    } finally {
      this.isRefreshing.set(false);
    }
  }

  async handleAddRule(event: { url: string; maxPrice: number | null }): Promise<void> {
    try {
      await this.rulesService.createRule(event.url, event.maxPrice);
      if (typeof window !== 'undefined' && window.innerWidth <= 768) {
        this.isAddRuleOpen.set(false);
      }
    } catch {
      // Error handled in service
    }
  }

  initiateDelete(id: string): void {
    const target = this.rulesService.rules().find(r => r.id === id);
    if (target) {
      this.ruleToDelete.set(target);
    }
  }

  async handleConfirmDelete(): Promise<void> {
    const target = this.ruleToDelete();
    if (!target) return;
    this.isDeleting.set(true);
    try {
      await this.rulesService.deleteRule(target.id);
      this.ruleToDelete.set(null);
    } catch {
      // Error handled in service
    } finally {
      this.isDeleting.set(false);
    }
  }

  getDeleteMessage(): string {
    const target = this.ruleToDelete();
    return target ? `Are you sure you want to delete the search rule for "${target.url.substring(0, 50)}..."?` : '';
  }
}

<app-layout [activeTab]="activeTab()" (onTabChange)="activeTab.set($event)">
  @if (activeTab() === 'monitor') {
    <app-dashboard-monitor (onInitiateDelete)="initiateDelete($event)"></app-dashboard-monitor>
  }

  @if (activeTab() === 'logs') {
    <app-dashboard-logs></app-dashboard-logs>
  }

  @if (activeTab() === 'settings') {
    <app-dashboard-settings></app-dashboard-settings>
  }

  <app-confirm-modal
    [isOpen]="!!ruleToDelete()"
    title="Delete Search Rule"
    [message]="getDeleteMessage()"
    confirmLabel="Delete Rule"
    cancelLabel="Cancel"
    [isLoading]="isDeleting()"
    (onConfirm)="handleConfirmDelete()"
    (onCancel)="ruleToDelete.set(null)"
  ></app-confirm-modal>
</app-layout>
