// DealHunter.Web/src/shared/layout/Sidebar.tsx
import React from 'react';
import { Terminal, Sliders, ShieldCheck } from 'lucide-react';

interface SidebarProps {
  activeTab?: string;
  onTabChange?: (tab: string) => void;
}

export const Sidebar: React.FC<SidebarProps> = ({
  activeTab = 'monitor',
  onTabChange,
}) => {
  const navItemStyle = (isActive: boolean): React.CSSProperties => ({
    padding: '0.8rem 1rem',
    color: isActive ? 'var(--neon-green)' : 'var(--text-main)',
    background: isActive ? 'rgba(57, 255, 20, 0.1)' : 'transparent',
    borderLeft: isActive ? '3px solid var(--neon-green)' : '3px solid transparent',
    textDecoration: 'none',
    fontSize: '1rem',
    fontFamily: 'var(--font-mono)',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    outline: 'none',
    border: 'none',
    textShadow: isActive ? '0 0 8px rgba(57, 255, 20, 0.5)' : 'none',
  });

  return (
    <aside className="app-sidebar">
      <nav className="sidebar-nav">
        <button
          className={activeTab === 'monitor' ? 'active' : ''}
          style={navItemStyle(activeTab === 'monitor')}
          onClick={() => onTabChange?.('monitor')}
        >
          <Terminal size={18} /> Monitor
        </button>
        <button
          className={activeTab === 'logs' ? 'active' : ''}
          style={navItemStyle(activeTab === 'logs')}
          onClick={() => onTabChange?.('logs')}
        >
          <Sliders size={18} /> Logs
        </button>
        <button
          className={activeTab === 'settings' ? 'active' : ''}
          style={navItemStyle(activeTab === 'settings')}
          onClick={() => onTabChange?.('settings')}
        >
          <ShieldCheck size={18} /> Settings
        </button>
      </nav>

      <div className="terminal-info-box">
        <div>User: Admin</div>
        <div>Version: 1.0.0</div>
      </div>
    </aside>
  );
};

// DealHunter.Web/src/app/shared/layout/sidebar/sidebar.component.ts
import { Component, input, output } from '@angular/core';
import { LucideTerminal, LucideSliders, LucideShieldCheck } from '@lucide/angular';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [LucideTerminal, LucideSliders, LucideShieldCheck],
  template: `
    <aside class="app-sidebar">
      <nav class="sidebar-nav">
        <button
          [class.active]="activeTab() === 'monitor'"
          class="nav-item"
          (click)="onTabChange.emit('monitor')"
        >
          <svg lucideIcon="terminal" [size]="18"></svg> Monitor
        </button>
        <button
          [class.active]="activeTab() === 'logs'"
          class="nav-item"
          (click)="onTabChange.emit('logs')"
        >
          <svg lucideIcon="sliders" [size]="18"></svg> Logs
        </button>
        <button
          [class.active]="activeTab() === 'settings'"
          class="nav-item"
          (click)="onTabChange.emit('settings')"
        >
          <svg lucideIcon="shield-check" [size]="18"></svg> Settings
        </button>
      </nav>

      <div class="terminal-info-box">
        <div>User: Admin</div>
        <div>Version: 1.0.0</div>
      </div>
    </aside>
  `,
  styles: [`
    :host {
      display: block;
    }
    .app-sidebar {
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      height: 100%;
    }
    .sidebar-nav {
      display: flex;
      flex-direction: column;
      gap: 0.2rem;
    }
    .nav-item {
      padding: 0.8rem 1rem;
      color: var(--text-main);
      background: transparent;
      border-left: 3px solid transparent;
      text-decoration: none;
      font-size: 1rem;
      font-family: var(--font-mono);
      transition: all 0.3s ease;
      cursor: pointer;
      display: flex;
      align-items: center;
      gap: 8px;
      outline: none;
      border-top: none;
      border-right: none;
      border-bottom: none;
      text-shadow: none;
      width: 100%;
      text-align: left;
    }
    .nav-item:hover {
      background: rgba(255, 255, 255, 0.05);
      color: var(--neon-green);
    }
    .nav-item.active {
      color: var(--neon-green);
      background: rgba(57, 255, 20, 0.1);
      border-left-color: var(--neon-green);
      text-shadow: 0 0 8px rgba(57, 255, 20, 0.5);
    }
    .terminal-info-box {
      padding: 1rem;
      font-family: var(--font-mono);
      font-size: 0.8rem;
      color: var(--text-muted);
      border-top: 1px solid rgba(57, 255, 20, 0.2);
    }
  `]
})
export class SidebarComponent {
  activeTab = input<string>('monitor');
  onTabChange = output<string>();
}
