// DealHunter.Web/src/shared/components/ui/Panel.tsx
import React from 'react';

interface PanelProps {
  title?: string;
  action?: React.ReactNode;
  children: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Panel: React.FC<PanelProps> = ({
  title,
  action,
  children,
  className = '',
  style,
}) => {
  return (
    <section className={`panel ${className}`} style={style}>
      {(title || action) && (
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '1rem',
          }}
        >
          {title && <h2 style={{ margin: 0 }}>&gt; {title}</h2>}
          {action && <div>{action}</div>}
        </div>
      )}
      {children}
    </section>
  );
};

// DealHunter.Web/src/app/shared/components/ui/panel/panel.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-panel',
  standalone: true,
  template: `
    <section class="panel">
      @if (title() || hasAction()) {
        <div class="panel-header">
          @if (title()) {
            <h2 class="panel-title">&gt; {{ title() }}</h2>
          }
          <div class="panel-action">
            <ng-content select="[panel-action]"></ng-content>
          </div>
        </div>
      }
      <ng-content></ng-content>
    </section>
  `,
  styles: [`
    :host {
      display: block;
    }
    .panel-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1rem;
    }
    .panel-title {
      margin: 0;
    }
  `]
})
export class PanelComponent {
  title = input<string>('');
  hasAction = input<boolean>(false);
}
