// DealHunter.Web/src/app/features/rules/add-rule-form/add-rule-form.component.ts
import { Component, output, signal } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormControl, Validators, AbstractControl, ValidationErrors } from '@angular/forms';
import { InputComponent } from '../../../shared/components/ui/input/input.component';
import { ButtonComponent } from '../../../shared/components/ui/button/button.component';
import { LucidePlus } from '@lucide/angular';

function olxUrlValidator(control: AbstractControl): ValidationErrors | null {
  const val = control.value;
  if (!val || typeof val !== 'string') return null;
  if (!val.includes('olx.pl')) {
    return { invalidOlxUrl: true };
  }
  return null;
}

@Component({
  selector: 'app-add-rule-form',
  standalone: true,
  imports: [ReactiveFormsModule, InputComponent, ButtonComponent, LucidePlus],
  template: `
    <form [formGroup]="form" (ngSubmit)="handleSubmit()">
      <app-input
        id="url"
        label="OLX Search URL"
        placeholder="https://www.olx.pl/d/oferta/..."
        formControlName="url"
        [error]="getErrorMessage()"
      ></app-input>

      <app-input
        id="max-price"
        label="Max Price (PLN, optional)"
        type="number"
        placeholder="e.g. 1500"
        formControlName="maxPrice"
      ></app-input>

      <app-button type="submit" variant="primary" class="full-width-mobile">
        <span class="btn-content">
          <svg lucidePlus [size]="18"></svg> Add Rule
        </span>
      </app-button>
    </form>
  `,
  styles: [`
    :host {
      display: block;
    }
    .btn-content {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      justify-content: center;
    }
  `]
})
export class AddRuleFormComponent {
  onAddRule = output<{ url: string; maxPrice: number | null }>();
  customError = signal<string>('');

  form = new FormGroup({
    url: new FormControl('', { nonNullable: true, validators: [Validators.required, olxUrlValidator] }),
    maxPrice: new FormControl<string | number>('', { nonNullable: true })
  });

  getErrorMessage(): string {
    if (this.customError()) return this.customError();
    const ctrl = this.form.controls.url;
    if (ctrl.touched && ctrl.invalid) {
      if (ctrl.hasError('required')) return 'Target URL is required';
      if (ctrl.hasError('invalidOlxUrl')) return 'URL must be a valid OLX.pl link';
    }
    return '';
  }

  handleSubmit(): void {
    this.customError.set('');
    if (this.form.invalid) {
      this.form.controls.url.markAsTouched();
      if (this.form.controls.url.hasError('required')) {
        this.customError.set('Target URL is required');
      } else if (this.form.controls.url.hasError('invalidOlxUrl')) {
        this.customError.set('URL must be a valid OLX.pl link');
      }
      return;
    }

    const rawUrl = this.form.controls.url.value.trim();
    const rawPrice = this.form.controls.maxPrice.value;
    const parsedPrice = rawPrice !== '' && rawPrice !== null && rawPrice !== undefined ? parseFloat(String(rawPrice)) : null;

    this.onAddRule.emit({ url: rawUrl, maxPrice: isNaN(parsedPrice as number) ? null : parsedPrice });
    this.form.reset({ url: '', maxPrice: '' });
  }
}

// DealHunter.Web/src/features/rules/components/AddRuleForm.tsx
import React, { useState } from 'react';
import { Input } from '@/shared/components/ui/Input';
import { Button } from '@/shared/components/ui/Button';
import { Plus } from 'lucide-react';

interface AddRuleFormProps {
  onAddRule: (url: string, maxPrice: number | null) => void;
}

export const AddRuleForm: React.FC<AddRuleFormProps> = ({ onAddRule }) => {
  const [url, setUrl] = useState('');
  const [maxPrice, setMaxPrice] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!url.trim()) {
      setError('Target URL is required');
      return;
    }

    if (!url.includes('olx.pl')) {
      setError('URL must be a valid OLX.pl link');
      return;
    }

    setError('');
    const parsedPrice = maxPrice ? parseFloat(maxPrice) : null;
    onAddRule(url.trim(), parsedPrice);
    setUrl('');
    setMaxPrice('');
  };

  return (
    <form onSubmit={handleSubmit}>
      <Input
        id="url"
        label="OLX Search URL"
        placeholder="https://www.olx.pl/d/oferta/..."
        value={url}
        onChange={(e) => {
          setUrl(e.target.value);
          if (error) setError('');
        }}
        error={error}
        required
      />
      <Input
        id="max-price"
        label="Max Price (PLN, optional)"
        type="number"
        placeholder="e.g. 1500"
        value={maxPrice}
        onChange={(e) => setMaxPrice(e.target.value)}
      />
      <Button type="submit" variant="primary" className="full-width-mobile">
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', justifyContent: 'center' }}>
          <Plus size={18} /> Add Rule
        </span>
      </Button>
    </form>
  );
};
