// DealHunter.Web/src/app/features/rules/rule-card/rule-card.component.ts
import { Component, input, output } from '@angular/core';
import { RuleItem } from '../../../shared/models/rule.model';
import { BadgeComponent } from '../../../shared/components/ui/badge/badge.component';
import { ButtonComponent } from '../../../shared/components/ui/button/button.component';
import { LucideExternalLink, LucideTrash2 } from '@lucide/angular';

@Component({
  selector: 'app-rule-card',
  standalone: true,
  imports: [BadgeComponent, ButtonComponent, LucideExternalLink, LucideTrash2],
  template: `
    <div class="rule-card">
      <div class="rule-info">
        <div class="rule-header-row">
          <span class="rule-title">{{ getRuleTitle(rule().url) }}</span>
          @if (rule().maxPrice !== null && rule().maxPrice !== undefined) {
            <app-badge variant="green">Max: {{ rule().maxPrice!.toLocaleString() }} PLN</app-badge>
          }
        </div>
        <a
          [href]="rule().url"
          target="_blank"
          rel="noopener noreferrer"
          class="rule-url"
        >
          {{ getTruncatedUrl(rule().url) }} <svg lucideExternalLink [size]="14"></svg>
        </a>
        <span class="rule-date">Created: {{ rule().createdAt }}</span>
      </div>
      <app-button
        variant="danger"
        class="full-width-mobile"
        (onClick)="onDelete.emit(rule().id)"
      >
        <span class="btn-content">
          <svg lucideTrash2 [size]="16"></svg> Delete
        </span>
      </app-button>
    </div>
  `,
  styles: [`
    :host {
      display: block;
    }
    .rule-header-row {
      display: flex;
      gap: 8px;
      align-items: center;
      flex-wrap: wrap;
    }
    .rule-title {
      color: var(--neon-purple);
      font-weight: bold;
      font-family: var(--font-heading);
      font-size: 1rem;
      text-transform: capitalize;
    }
    .rule-date {
      color: var(--text-muted);
      font-size: 0.85rem;
    }
    .btn-content {
      display: inline-flex;
      align-items: center;
      gap: 0.4rem;
      justify-content: center;
    }
  `]
})
export class RuleCardComponent {
  rule = input.required<RuleItem>();
  onDelete = output<string>();

  getTruncatedUrl(url: string): string {
    return url.length > 50 ? `${url.substring(0, 50)}...` : url;
  }

  getRuleTitle(url: string): string {
    try {
      const urlObj = new URL(url);
      const search = urlObj.searchParams.get('q') || urlObj.searchParams.get('search[query]');
      if (search) {
        return search.replace(/-/g, ' ');
      }
      const pathname = urlObj.pathname.replace(/^\/|\/$/g, '');
      const segments = pathname.split('/').filter(Boolean);
      if (segments.length > 0) {
        const lastSegment = segments[segments.length - 1];
        const cleanName = lastSegment
          .replace(/^q-/, '')
          .replace(/\.html$/, '')
          .replace(/-\d+$/, '')
          .replace(/-/g, ' ');
        if (cleanName.length > 0) {
          return cleanName.charAt(0).toUpperCase() + cleanName.slice(1);
        }
      }
    } catch {
      // Fallback if invalid URL string
    }
    return 'OLX Search Rule';
  }
}

// DealHunter.Web/src/features/rules/components/RuleCard.tsx
import React from 'react';
import { RuleItem } from '@/shared/types/models';
import { Badge } from '@/shared/components/ui/Badge';
import { Button } from '@/shared/components/ui/Button';
import { ExternalLink, Trash2 } from 'lucide-react';

interface RuleCardProps {
  rule: RuleItem;
  onDelete: (id: string) => void;
}

export const RuleCard: React.FC<RuleCardProps> = ({ rule, onDelete }) => {
  const getRuleTitle = (url: string): string => {
    try {
      const urlObj = new URL(url);
      const search = urlObj.searchParams.get('q') || urlObj.searchParams.get('search[query]');
      if (search) {
        return search.replace(/-/g, ' ');
      }
      const pathname = urlObj.pathname.replace(/^\/|\/$/g, '');
      const segments = pathname.split('/').filter(Boolean);
      if (segments.length > 0) {
        const lastSegment = segments[segments.length - 1];
        const cleanName = lastSegment
          .replace(/^q-/, '')
          .replace(/\.html$/, '')
          .replace(/-\d+$/, '')
          .replace(/-/g, ' ');
        if (cleanName.length > 0) {
          return cleanName.charAt(0).toUpperCase() + cleanName.slice(1);
        }
      }
    } catch {
      // Fallback if invalid URL string
    }
    return 'OLX Search Rule';
  };

  const title = getRuleTitle(rule.url);
  const truncatedUrl = rule.url.length > 50 ? `${rule.url.substring(0, 50)}...` : rule.url;

  return (
    <div
      className="rule-card"
      onMouseEnter={(e) => {
        e.currentTarget.style.background = 'rgba(188, 19, 254, 0.1)';
        e.currentTarget.style.borderLeftColor = 'var(--neon-green)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.background = 'rgba(255, 255, 255, 0.03)';
        e.currentTarget.style.borderLeftColor = 'var(--neon-purple)';
      }}
    >
      <div className="rule-info">
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center', flexWrap: 'wrap' }}>
          <span
            style={{
              color: 'var(--neon-purple)',
              fontWeight: 'bold',
              fontFamily: 'var(--font-heading)',
              fontSize: '1rem',
              textTransform: 'capitalize',
            }}
          >
            {title}
          </span>
          {rule.maxPrice !== null && (
            <Badge variant="green">Max: {rule.maxPrice.toLocaleString()} PLN</Badge>
          )}
        </div>
        <a
          href={rule.url}
          target="_blank"
          rel="noopener noreferrer"
          className="rule-url"
        >
          {truncatedUrl} <ExternalLink size={14} />
        </a>
        <span style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>
          Created: {rule.createdAt}
        </span>
      </div>
      <Button
        variant="danger"
        className="full-width-mobile"
        onClick={() => onDelete(rule.id)}
      >
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', justifyContent: 'center' }}>
          <Trash2 size={16} /> Delete
        </span>
      </Button>
    </div>
  );
};
